- name: Install components
  yum:
    name: unzip
    state: latest

- name: Download promtail.service v2.0.0
  get_url:
    url: "{{ grafana_promtail_url }}"
    dest: "/usr/local/bin/"

- name: Extract Promtail archive
  unarchive:
    src: "/usr/local/bin/promtail-linux-amd64.zip"
    dest: /usr/local/bin/
    remote_src: yes

- name: Rename promtail-linux-amd64 to promtail
  command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail

- name: Changing perm of "promtail", adding "a+x"
  file: dest=/usr/local/bin/promtail mode=a+x

- name: Create promtail config file
  template:
    src: templates/promtail.config.j2
    dest: /usr/local/bin/config-promtail.yaml

- name: Create promtail service file
  template:
    src: templates/promtail.service.j2
    dest: /etc/systemd/system/promtail.service

- name: Open promtail port on the firewall
  firewalld:
    port: 9080/tcp
    permanent: true
    state: enabled

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Start and enable Promtail
  service:
    daemon_reload: yes
    name: promtail
    state: started
    enabled: yes
