---

- name: Install components
  yum:
    name: unzip
    state: latest

- name: Prepere yum file for grafana install 
  template:
    src: templates/grafana.service.j2
    dest: /etc/yum.repos.d/grafana.repo

- name: Install grafana-server
  yum:
    name: grafana
    state: latest

- name: Start and enable Grafana
  service:
    daemon_reload: yes
    name: grafana-server
    state: started
    enabled: yes

- name: Open grafana port on the firewall
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
